items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-master-
    labels:
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.xlarge
        image: KVM-Ubt16.04-Srv-x64
        sshUserName: cloudusr
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: bd96e01b-3fba-4dd7-92cb-6feeaf018817
        floatingIP: 9.20.204.233
        securityGroups:
        - uuid: 5a88fd7f-1cef-4ef1-847d-aeb87caba17a
        - uuid: 6ac9e9b9-4856-4f19-ba5c-2d00d006796e
        - uuid: 71cfb15e-e0fd-4d54-be0b-abbf026f3bfd
        userDataSecret:
          name: master-user-data
          namespace: openstack-provider-system
        trunk: false
    versions:
      kubelet: 1.14.0
      controlPlane: 1.14.0
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: openstack-node-
    labels:
      set: node
  spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.medium
        image: KVM-Ubt16.04-Srv-x64
        sshUserName: cloudusr
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: bd96e01b-3fba-4dd7-92cb-6feeaf018817
        floatingIP: 9.20.205.49
        securityGroups:
        - uuid: 5a88fd7f-1cef-4ef1-847d-aeb87caba17a
        - uuid: 6ac9e9b9-4856-4f19-ba5c-2d00d006796e
        - uuid: 71cfb15e-e0fd-4d54-be0b-abbf026f3bfd
        userDataSecret:
          name: worker-user-data
          namespace: openstack-provider-system
        trunk: false
    versions:
      kubelet: 1.14.0
