heat_template_version: 2013-05-23
description: >
  Heat template to deploy Docker containers to an existing host
resources:
  nginx-01:
    type: IBMInc::EGO::Service 
    properties:
      image: marouen/mysql
      port_specs:
        - 3306
      docker_endpoint: 'tcp://127.0.0.1:3128'
