heat_template_version: 2013-05-23

description: >
  Dockerize a multi-node application with OpenStack Heat.
  This template defines two docker containers running
  apache with php and mysql database.

resources:
  sql_server_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      resource:
        type: docker_stack.yaml
  up-policy:
    type: OS::Heat::ScalingPolicy
    properties:
      auto_scaling_group_id: {get_resource: sql_server_group}
      adjustment_type: change_in_capacity
      scaling_adjustment: 1
  down-policy:
    type: OS::Heat::ScalingPolicy
    properties:
      auto_scaling_group_id: {get_resource: sql_server_group}
      adjustment_type: change_in_capacity
      scaling_adjustment: -1

outputs:
  url:
    description: Public address of apache
    value:
      template: http://9.111.242.59
