apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: myolm-operator-subsription
  namespace: marketplace
spec:
  channel: alpha
  name: memcached-operator
  source: myolm-operators
  sourceNamespace: marketplace
