apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: myolm-operators
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: myolm
